version: '3'

services:
  mysql-desafio-pfa:
    container_name: mysql-desafio-pfa
    build: ./mysql
    volumes: 
      - ./db:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks: 
      - pfa-desafio
  
  node-desafio-pfa:
    container_name: node-desafio-pfa
    build: ./node
    volumes:
      - ./node:/home/node/app
      # - /home/node/app/node_modules
    depends_on: 
      - mysql-desafio-pfa
    networks: 
      - pfa-desafio

  nginx-desafio-pfa:
    container_name: nginx-desafio-pfa
    build: ./nginx
    ports:
      - 8080:80
    depends_on: 
      - node-desafio-pfa
    networks: 
      - pfa-desafio

networks: 
  pfa-desafio:
    driver: bridge